Repository gregnb/mui-datatables, pull requests merged in 2019-09, with the labels that each got.

#890 Issue 878 Overwriting Props
  package-lock.json
  package.json
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: bug

#896 Bugfix/Issue 365
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: bug

#912 Fix issue with scroll full height using incorrect class name
  src/MUIDataTable.js
Labels: bug

#863 Fix #778 Enhancement/switch between examples
  examples/Router/ExamplesGrid.js
  examples/Router/index.js
  examples/array-value-columns/index.js
  examples/column-filters/index.js
  examples/column-options-update/index.js
  examples/component/index.js
  examples/csv-export/index.js
  examples/custom-action-columns/index.js
  examples/customize-columns/index.js
  examples/customize-filter/index.js
  examples/customize-footer/index.js
  examples/customize-rows/index.js
  examples/customize-search-render/index.js
  examples/customize-search/index.js
  examples/customize-sorting/index.js
  examples/customize-styling/index.js
  examples/customize-toolbar/index.js
  examples/customize-toolbarselect/index.js
  examples/data-as-objects/index.js
  examples/examples.js
  examples/expandable-rows/index.js
  examples/fixed-header/index.js
  examples/hide-columns-print/index.js
  examples/on-download/index.js
  examples/on-table-init/index.js
  examples/resizable-columns/index.js
  examples/selectable-rows/index.js
  examples/serverside-options/index.js
  examples/serverside-pagination/index.js
  examples/simple-no-toolbar/index.js
  examples/simple/index.js
  examples/text-localization/index.js
  examples/themes/index.js
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement, lgtm

#876 Fix for #869
  README.md
  examples/customize-search-render/CustomSearchRender.js
  src/MUIDataTable.js
  src/components/TableSearch.js
  src/components/TableToolbar.js
Labels: bug, lgtm

#877 Fix for #873
  src/utils.js
Labels: bug, lgtm

#881 Fix for 880
  src/MUIDataTable.js
  src/components/TableFilter.js
  test/MUIDataTable.test.js
Labels: bug, enhancement, lgtm

#882 Fix for 868 (selectableRowsHeader option)
  README.md
  examples/selectable-rows/index.js
  src/MUIDataTable.js
  src/components/TableHead.js
  src/components/TableSelectCell.js
Labels: lgtm, new feature

#888 #887 and#878
  README.md
  src/MUIDataTable.js
  src/components/TableHead.js
  src/components/TableHeadCell.js
Labels: enhancement, lgtm, new feature

#892 Add failing test for sorting columns with undefined data
  test/MUIDataTable.test.js
Labels: enhancement, lgtm

#902 Issue 901 - Fix inconsistent table meta
  examples/custom-action-columns/index.js
  src/MUIDataTable.js
Labels: bug, lgtm
