Repository gregnb/mui-datatables, pull requests merged in 2019-05, with the labels that each got.

#588 Make tooltips consistent
  src/components/TableToolbar.js
Labels: lgtm

#599 Add test for serverSide=true with xhr
  test/MUIDataTable.test.js
Labels: enhancement

#590 Added collaboration info
  README.md
Labels: lgtm

#587 Enhancement/issue 193 424 skip row delete
  README.md
  examples/selectable-rows/index.js
  src/MUIDataTable.js
  test/MUIDataTable.test.js
  webpack.config.js
Labels: lgtm

#501 Added options for data manipulation onDownload of CSV file
  README.md
  examples/on-download/index.js
  src/MUIDataTable.js
  src/utils.js
  test/MUIDataTableToolbar.test.js
Labels: lgtm

#601 Add additional input examples for customBodyRender
  examples/component/index.js
Labels: enhancement

#560 Fix for Issue 483
  examples/column-filters/index.js
  src/MUIDataTable.js
  src/components/TableFilter.js
  src/components/TableFilterList.js
  test/MUIDataTable.test.js
  webpack.config.js
Labels: Need review

#603 Add searchText option to initialise datatable with search text
  README.md
  examples/customize-search/index.js
  src/MUIDataTable.js
  src/components/TableSearch.js
  src/components/TableToolbar.js
  test/MUIDataTableSearch.test.js
  test/MUIDataTableToolbar.test.js
Labels: enhancement, lgtm

#606 Bugfix/issues 561 and 600 toolbar problems
  package-lock.json
  src/components/Popover.js
  src/components/TableFilterList.js
  src/components/TableToolbar.js
  test/MUIDataTable.test.js
Labels: bug, lgtm

#609 Document option for hiding column from 'View Column' list
  README.md
Labels: lgtm

#629 header wrap fix
  src/components/TableHeadCell.js
  src/components/TableHeadRow.js
Labels: lgtm

#631 Bugfix/issue 587 fix duplicate call
  package-lock.json
  src/MUIDataTable.js
Labels: lgtm

#647 Bugfix/search text issues
  examples/customize-search/index.js
  src/MUIDataTable.js
  src/components/TableSearch.js
  src/components/TableToolbar.js
  test/MUIDataTable.test.js
  test/MUIDataTableSearch.test.js
  test/MUIDataTableToolbar.test.js
Labels: bug

#641 Bugfix/remove deprecated rollup config option
  package-lock.json
  package.json
  rollup.config.js
  src/components/TableHeadCell.js
  src/components/TableHeadRow.js
Labels: lgtm

#622 add onTableInit callback
  README.md
  examples/on-table-init/index.js
  rollup.config.js
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: lgtm

#624 renderMultiselect filter type for null values
  src/components/TableFilter.js
Labels: lgtm

#640 Improve grid spacing in filters dialog
  src/components/TableFilter.js
Labels: lgtm
