Repository gregnb/mui-datatables, pull requests merged in 2019-06, with the labels that each got.

#607 Add fullRowTrigger option to allow action anywhere on row click
  README.md
  examples/expandable-rows/index.js
  src/MUIDataTable.js
  src/components/TableBody.js
  src/components/TableBodyRow.js
  src/components/TableSelectCell.js
Labels: lgtm

#648 Fix issue #610 about count from server does not refresh
  examples/serverside-pagination/index.js
  src/MUIDataTable.js
  webpack.config.js
Labels: lgtm

#669 Handle undefined values for multiselect filters
  src/components/TableFilter.js
Labels: lgtm

#677 Bugfix/issue 672 more robust icon fix
  examples/resizable-columns/index.js
  src/components/TableHeadCell.js
Labels: lgtm

#683 Feature/issue 430 pr 578 custom filter logic
  README.md
  examples/column-filters/index.js
  examples/customize-filter/index.js
  src/MUIDataTable.js
  test/MUIDataTable.test.js
  webpack.config.js
Labels: lgtm

#686 Add tests for selectable and expandable row functionality
  test/MUIDataTableBody.test.js
Labels: enhancement

#619 Allow for accessing nested object data.
  examples/data-as-objects/index.js
  package-lock.json
  src/MUIDataTable.js
Labels: enhancement, lgtm

#664 Updates 'options' in componentDidUpdate
  src/MUIDataTable.js
Labels: lgtm

#675 Move the column argument to the correct position
  src/MUIDataTable.js
Labels: lgtm

#668 Undo any deep overwriting of array
  src/MUIDataTable.js
Labels: enhancement, lgtm

#685 Fix issue #370
  src/MUIDataTable.js
Labels: lgtm
