Repository gregnb/mui-datatables, pull requests merged in 2019-08, with the labels that each got.

#738 Fix for 737
  examples/customize-filter/index.js
  src/MUIDataTable.js
Labels: enhancement, lgtm

#793 Set selectable row checkbox color through attribute
  src/components/TableSelectCell.js
Labels: enhancement, lgtm

#794 Enhancement/pr 725 issue 440 download display only
  examples/csv-export/index.js
  src/MUIDataTable.js
  src/components/TableToolbar.js
Labels: enhancement, lgtm

#801 Feature/issue 755 add rows expanded option
  README.md
  examples/expandable-rows/index.js
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: lgtm, new feature

#802 Enhancement/pr 667 updated
  src/components/TableBody.js
  src/components/TableFilter.js
  src/components/TablePagination.js
  src/components/TableSearch.js
  src/components/TableToolbar.js
Labels: enhancement, lgtm

#715 add test for #711
  test/MUIDataTable.test.js
Labels: lgtm

#763 Page reset762
  src/MUIDataTable.js
Labels: lgtm

#771 Allow to custom table search render
  README.md
  examples/customize-search-render/CustomSearchRender.js
  examples/customize-search-render/index.js
  src/MUIDataTable.js
  src/components/TableToolbar.js
  test/MUIDataTableToolbar.test.js
Labels: lgtm

#791 Fix issue with width on custom filter component
  src/components/TableFilter.js
Labels: lgtm

#814 Enhancement/pr 659 sort multiple
  src/MUIDataTable.js
Labels: enhancement, lgtm

#818 Bugfix/issue 817 fix rows selected
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: bug, lgtm

#837 Fix isRowSelectable update issues
  package-lock.json
  package.json
  src/MUIDataTable.js
Labels: bug, lgtm

#824 Fix available 'rowsPerPageOptions' in documentation
  README.md
Labels: lgtm

#825 Enable functionality to limit maximum number of rows to select
  README.md
  examples/selectable-rows/index.js
  src/MUIDataTable.js
  src/components/TableBody.js
  test/MUIDataTableBody.test.js
Labels: lgtm

#828 Added options parameter to customFooter callback
  README.md
  examples/customize-footer/CustomFooter.js
  examples/customize-footer/index.js
  src/components/TableFooter.js
  src/components/TablePagination.js
Labels: lgtm

#829 Fix for Memory Leak in TableToolbar
  src/MUIDataTable.js
  src/components/TableToolbar.js
  src/styled.js
  test/MUIDataTableToolbar.test.js
Labels: lgtm

#838 List downloadOptions keys in docs for usability
  README.md
Labels: lgtm

#847 Silence deprecation warning by using the unsafe API
  docs/utils/withRoot.js
  src/MUIDataTable.js
  src/components/Popover.js
Labels: enhancement, lgtm

#848 Enhancement/pr 687 updated
  examples/column-options-update/index.js
  package-lock.json
  test/MUIDataTable.test.js
Labels: enhancement, lgtm

#827 Added support for Shift + Click selection of rows
  src/MUIDataTable.js
  src/components/TableBody.js
  test/MUIDataTable.test.js
  test/MUIDataTableBody.test.js
Labels: lgtm, new feature

#832 Fix to make tests compatible with Material UI v3 and v4
  test/MUIDataTable.test.js
  test/setup-mocha-env.js
Labels: enhancement, lgtm

#836 Fixes for 676 and 595
  src/components/TableToolbar.js
  src/components/TableToolbarSelect.js
Labels: enhancement, lgtm

#852 [Enhancement] Fixed issue #447 (Search box - Default Text)
  README.md
  examples/customize-search/index.js
  src/MUIDataTable.js
  src/components/TableSearch.js
  test/MUIDataTableSearch.test.js
  webpack.config.js
Labels: lgtm, new feature

#859 Fix for #858
  src/components/TableHeadCell.js
Labels: bug, enhancement, lgtm

#860 Improve documentation and plumbing for rows selection
  README.md
  src/MUIDataTable.js
  src/components/TableBody.js
Labels: enhancement, lgtm

#883 PR-833 Code Cleanup Continued
  src/MUIDataTable.js
Labels: enhancement, lgtm

#866 Refine sortDirection and documentation to support 'none' option
  README.md
  src/MUIDataTable.js
  src/components/TableHeadCell.js
  test/MUIDataTable.test.js
Labels: enhancement, lgtm

#867 Feature/issue 759 responsive options
  README.md
  examples/array-value-columns/index.js
  examples/component/index.js
  examples/customize-filter/index.js
  examples/customize-rows/index.js
  examples/expandable-rows/index.js
  examples/fixed-header/index.js
  examples/hide-columns-print/index.js
  examples/on-download/index.js
  examples/on-table-init/index.js
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: lgtm, new feature

#885 Correct cell background for stacked and scroll
  src/components/TableBodyCell.js
  src/components/TableSelectCell.js
Labels: bug, lgtm
