Repository gregnb/mui-datatables, pull requests merged in 2019-11, with the labels that each got.

#670 Add table properties option
  README.md
  package-lock.json
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: lgtm, new feature

#874 Added disableToolbarSelect option
  README.md
  src/MUIDataTable.js
  src/components/TableHead.js
  test/MUIDataTable.test.js
Labels: lgtm, new feature

#910 No Pointer style cursor for table head when no hint or sorting
  src/components/TableHeadCell.js
Labels: enhancement, lgtm

#986 Serverside sorting example
  examples/examples.js
  examples/serverside-sorting/cities.js
  examples/serverside-sorting/index.js
  package-lock.json
Labels: enhancement, lgtm

#1004 Update .gitignore and ignoring yarn.lock
  .gitignore
Labels: enhancement, lgtm

#1006 add test case to verify reset type
  test/MUIDataTable.test.js
Labels: enhancement, lgtm

#1025 Hide toggle button when the row is not expandable
  examples/expandable-rows/index.js
  src/components/TableBody.js
  src/components/TableSelectCell.js
Labels: enhancement, lgtm

#1064 Bugfix/issue 1052 csv download issues
  src/components/TableToolbar.js
  src/utils.js
  test/utils.test.js
Labels: bug, enhancement, lgtm

#1067 Feature/issue 937 array and custom update filter support
  README.md
  examples/column-filters/index.js
  examples/column-options-update/index.js
  examples/customize-filter/index.js
  src/MUIDataTable.js
  src/components/TableFilterList.js
  test/MUIDataTable.test.js
Labels: enhancement, lgtm, new feature

#889 Feature/issue 871 (setCellHeaderProps) and Feature/issue 714 (setTableProps)
  README.md
  examples/customize-styling/index.js
  src/MUIDataTable.js
  src/components/TableBodyCell.js
  src/components/TableHead.js
  src/components/TableHeadCell.js
  test/MUIDataTable.test.js
  test/MUIDataTableHeadCell.test.js
Labels: bug, enhancement, lgtm, new feature

#1069 Update webpack dev server and related dependencies
  package-lock.json
  package.json
  src/MUIDataTable.js
  src/components/TableBody.js
  src/components/TableBodyCell.js
  src/components/TableHead.js
  test/MUIDataTable.test.js
  test/MUIDataTableHeadCell.test.js
  test/utils.test.js
Labels: dependencies, enhancement, lgtm

#1071 Feature/issue 1036 fixed header
  README.md
  examples/fixed-header/index.js
  src/MUIDataTable.js
  src/components/TableBody.js
  src/components/TableHead.js
  src/components/TableHeadCell.js
  src/components/TableSelectCell.js
  test/MUIDataTableHead.test.js
Labels: lgtm, new feature

#1081 Improve documentation
  README.md
Labels: enhancement, lgtm

#1084 Improve deprecation warnings and defaults for fixed header
  src/MUIDataTable.js
Labels: enhancement, lgtm
