Repository gregnb/mui-datatables, pull requests merged in 2019-10, with the labels that each got.

#861 Feature/issue 841 on rows expand
  README.md
  examples/expandable-rows/index.js
  src/MUIDataTable.js
  test/MUIDataTable.test.js
Labels: lgtm, new feature

#862 Feature/issue 841 is row expandable
  README.md
  examples/expandable-rows/index.js
  src/MUIDataTable.js
  src/components/TableBody.js
  test/MUIDataTableBody.test.js
Labels: lgtm, new feature

#893 Feature/Allow to display search bar from init
  README.md
  src/MUIDataTable.js
  src/components/TableToolbar.js
  test/MUIDataTableToolbar.test.js
Labels: lgtm, new feature

#913 Issue-857 Server Side Filters
  README.md
  examples/examples.js
  examples/serverside-filters/index.js
  src/MUIDataTable.js
  src/components/Popover.js
  src/components/TableFilter.js
  src/components/TableFilterList.js
  src/components/TableToolbar.js
  test/MUIDataTable.test.js
  test/MUIDataTableFilter.test.js
  test/MUIDataTableToolbar.test.js
Labels: enhancement, lgtm, new feature

#956 Fix invalid option deprecation checks
  src/MUIDataTable.js
Labels: bug, lgtm

#943 Improve naming in the router to make it easier to find examples
  examples/examples.js
Labels: enhancement, lgtm

#962 Remove obsolete/unused variables/props
  src/MUIDataTable.js
  src/components/TableHead.js
Labels: enhancement, lgtm

#964 Fix issue by properly checking for basic js objects and preserve displayed index
  src/components/TableToolbar.js
Labels: bug, lgtm

#970 adding button wrapper for icon
  src/components/TableSelectCell.js
Labels: enhancement, lgtm

#971 Allow sort direction of "none" to be applied multiple times
  src/MUIDataTable.js
Labels: bug, lgtm

#975 Upgrade testing performance and simplify
  test/MUIDataTable.test.js
Labels: enhancement, lgtm

#948 Fix issue where rows equal to row option would cause error
  src/MUIDataTable.js
  src/components/TableBody.js
  src/components/TablePagination.js
  src/utils.js
  test/MUIDataTablePagination.test.js
Labels: bug, lgtm, v3

#984 Fix crash on downloading empty table as CSV
  src/utils.js
Labels: bug, lgtm

#997 Stop mutating column.options props and support immutable data object
  src/MUIDataTable.js
Labels: enhancement, lgtm

#1008 Prevent overflows from preventing sticky headers
  src/MUIDataTable.js
Labels: bug, lgtm

#1010 Bugfix/issue 1005 prevent page reset on search close
  src/MUIDataTable.js
  src/components/TableToolbar.js
  test/MUIDataTable.test.js
  test/MUIDataTableToolbar.test.js
Labels: bug, lgtm

#1013 Bugfix/issue 1011 change error
  README.md
  src/MUIDataTable.js
Labels: bug, enhancement, lgtm

#1014 Bugfix/issue 994 properly calculate page
  src/utils.js
  test/utils.test.js
Labels: bug, enhancement, lgtm

#1034 Fix download row order when using display true options
  src/components/TableToolbar.js
Labels: bug, lgtm
