Repository gregnb/mui-datatables, pull requests merged in 2019-07, with the labels that each got.

#674 Fix for Issue #542
  README.md
  examples/csv-export/index.js
  src/MUIDataTable.js
  src/utils.js
  test/MUIDataTableToolbar.test.js
Labels: lgtm

#727 Issue warning instead of throwing an error
  src/components/TableBody.js
Labels: lgtm

#730 Use state and pull data out of render
  examples/on-table-init/index.js
Labels: enhancement, lgtm

#708 Custom filter - #688
  examples/customize-filter/index.js
  src/MUIDataTable.js
  src/components/TableFilter.js
  src/components/TableFilterList.js
  test/MUIDataTableFilter.test.js
Labels: lgtm

#741 Update filter options documentation for custom filter rendering
  README.md
Labels: enhancement

#744 Bugfix/issue 743 fix sort false display
  src/components/TableHeadCell.js
Labels: bug, enhancement

#766 Bugfix/issue 764 select click ignoring is selectable
  src/components/TableBody.js
  test/MUIDataTableBody.test.js
Labels: bug, lgtm

#768 Fix issue with selecting the proper row after sorting
  src/MUIDataTable.js
Labels: bug, lgtm

#769 Bugfix/issue 765 row click selection callbacks
  examples/selectable-rows/index.js
  src/components/TableBody.js
  test/MUIDataTableBody.test.js
Labels: bug, lgtm

#772 Fix issues with overflow for responsive stacked view
  src/MUIDataTable.js
Labels: bug, lgtm

#779 Fix regression with selection via checkbox
  src/components/TableBody.js
Labels: bug, lgtm
