Repository gregnb/mui-datatables, pull requests merged in 2020-05, with the labels that each got.

#1086 Updated table to make state persistent between renders
  examples/data-as-objects/index.js
  examples/simple/index.js
  src/MUIDataTable.js
Labels: needs review

#1224 Fix customize-filter example
  examples/customize-filter/index.js
Labels: enhancement, lgtm

#1192 Add documentation about filterList in the filterOptions section
  README.md
Labels: enhancement, lgtm

#1219 Mention peer dependencies
  README.md
Labels: enhancement, lgtm

#1171 Close icon to Popover & typo fix
  src/components/Popover.js
  src/components/TableFilter.js
  src/components/TableToolbar.js
Labels: enhancement, needs work

#1206 Move keydown close event to element
  src/components/TableSearch.js
Labels: breaking change, enhancement, v3

#1172 Continued/pr 1144 fix resizing
  src/MUIDataTable.js
  src/components/TableResize.js
Labels: bug

#1207 Prevent search icon focus on close
  src/components/TableToolbar.js
Labels: bug, lgtm

#1177 fix for #1164
  src/components/TableResize.js
Labels: bug, lgtm
