Repository gregnb/mui-datatables, pull requests merged in 2020-06, with the labels that each got.

#995 Refactor column direction conversion
  src/MUIDataTable.js
Labels: breaking change

#1154 Prevent skipping of heading level for Accessibility and standard semantic HTML purposes
  src/components/TableBody.js
Labels: enhancement, needs work

#602 Allow the toolbar to be rendered when a row is selected
  README.md
  src/MUIDataTable.js
Labels: v3

#1306 fix webpack config
  webpack.config.js
Labels: v3

#1310 Added sortOrder option (deprecating sortDirection on columns object)
  README.md
  examples/customize-columns/index.js
  examples/serverside-pagination/index.js
  src/MUIDataTable.js
  src/components/TableHead.js
  src/components/TableHeadCell.js
  test/MUIDataTable.test.js
Labels: v3

#1329 Draggable Columns
  README.md
  examples/draggable-columns/index.js
  examples/examples.js
  examples/resizable-columns/index.js
  package-lock.json
  package.json
  src/MUIDataTable.js
  src/components/TableBody.js
  src/components/TableBodyCell.js
  src/components/TableHead.js
  src/components/TableHeadCell.js
  src/components/TableResize.js
  src/components/TableSelectCell.js
  src/components/TableToolbar.js
  src/hooks/useColumnDrop.js
  test/MUIDataTableHead.test.js
  test/MUIDataTableHeadCell.test.js
  test/TableResize.test.js
Labels: new feature
