Repository gregnb/mui-datatables, pull requests merged in 2020-01, with the labels that each got.

#1053 Reset `activeIcon` to `null` when Search button is clicked while search is already open
  src/components/TableToolbar.js
  test/MUIDataTableToolbar.test.js
Labels: bug, enhancement, lgtm

#1059 Fix(#444): downloaded csv should show column "label", not "name"
  src/utils.js
Labels: bug, lgtm

#1073 Deprecation warnings
  src/MUIDataTable.js
  src/components/TableBody.js
  src/utils.js
Labels: enhancement, lgtm

#1122 Fix require path in test
  examples/serverside-sorting/index.js
Labels: bug, enhancement, lgtm

#1123 Enhancement/minor fixes
  examples/csv-export/index.js
  examples/customize-search-render/index.js
  examples/customize-styling/index.js
  examples/customize-toolbar/index.js
  examples/customize-toolbarselect/index.js
  examples/fixed-header/index.js
  examples/on-table-init/index.js
  examples/serverside-options/index.js
  examples/themes/index.js
  src/components/TableHeadCell.js
Labels: enhancement, lgtm

#1140 Bugfix/pr 1119 continued multiselect custom filter issues
  examples/customize-filter/index.js
  src/MUIDataTable.js
  src/components/TableFilterList.js
Labels: bug, enhancement, lgtm

#1153 Fix for Issue #1152 Table Search Accessibility
  src/components/TableSearch.js
Labels: bug, enhancement, lgtm

#1134 Feature/issue 1063 responsive options and table height
  README.md
  src/MUIDataTable.js
  src/components/TableBodyCell.js
  src/components/TableBodyRow.js
  src/components/TableHead.js
  src/components/TableToolbar.js
Labels: bug, enhancement, lgtm, new feature

#1155 Security/csv injection issue 1035
  src/utils.js
  test/utils.test.js
Labels: lgtm, security
